// SPDX-License-Identifier: MIT
pragma solidity ^0.8.35;

import {Test} from "forge-std/Test.sol";
import {SimpleAMM} from "../../src/SimpleAMM.sol";
import {MockERC20} from "../Mocks/MockERC20.sol";

/// @title SimpleAMM Handler Contract for Invariant Testing
/// @author Erick
/// @notice Handler contract that bounds and routes target operations for stateful fuzz testing.
/// @dev Acts as a simulated user interacting with SimpleAMM to prevent unnecessary reverts during fuzz runs.
contract SimpleAMMHandler is Test {
    /// @notice Target SimpleAMM instance being tested.
    SimpleAMM public amm;

    /// @notice Mock token 0 used in the pool.
    MockERC20 public token0;

    /// @notice Mock token 1 used in the pool.
    MockERC20 public token1;

    /// @notice Tracks the constant product constant k (reserve0 * reserve1) before a swap operation.
    /// @dev Set to 0 when liquidity changes, as deposits/withdrawals naturally alter the overall k value.
    uint256 public kLast;

    /// @notice Initializes the handler with target contract instances.
    /// @param _amm Address of the deployed SimpleAMM contract.
    /// @param _token0 Address of mock token 0.
    /// @param _token1 Address of mock token 1.
    constructor(SimpleAMM _amm, MockERC20 _token0, MockERC20 _token1) {
        amm = _amm;
        token0 = _token0;
        token1 = _token1;
    }

    /// @notice Mints tokens, grants approvals, and deposits liquidity into the AMM pool.
    /// @dev Bounds fuzz inputs and adjusts amount1 proportionally to match current pool reserves if total supply > 0.
    /// @param amount0 Unbounded initial input amount for token0 generated by the fuzzer.
    /// @param amount1 Unbounded initial input amount for token1 generated by the fuzzer.
    function addLiquidity(uint256 amount0, uint256 amount1) public {
        // Correctly assign the output of bound to variables
        amount0 = bound(amount0, 1e15, 10_000e18);
        amount1 = bound(amount1, 1e15, 10_000e18);

        // Adjust amount1 to maintain pool token ratio if pool is already active
        if (amm.totalSupply() > 0) {
            amount1 = (amount0 * amm.reserve1()) / amm.reserve0();
            if (amount1 == 0) return;
        }

        // Reset kLast since adding liquidity changes the constant product baseline
        kLast = 0;

        token0.mint(address(this), amount0);
        token1.mint(address(this), amount1);
        token0.approve(address(amm), amount0);
        token1.approve(address(amm), amount1);

        amm.addLiquidity(amount0, amount1);
    }

    /// @notice Mints input tokens, grants approval, and executes a token swap against the AMM pool.
    /// @dev Records the k value prior to swap execution to verify constant product invariant checks (k_after >= k_before).
    /// @param isToken0 Flag indicating whether token0 is the deposit token (true) or token1 (false).
    /// @param amountIn Unbounded input amount generated by the fuzzer to swap.
    function swap(bool isToken0, uint256 amountIn) public {
        amountIn = bound(amountIn, 1e15, 10_000e18);

        if (amm.reserve0() == 0 || amm.reserve1() == 0) return;

        // Record k before swap execution to check invariant k_after >= k_before
        kLast = amm.reserve0() * amm.reserve1();

        MockERC20 tokenIn = isToken0 ? token0 : token1;

        tokenIn.mint(address(this), amountIn);
        tokenIn.approve(address(amm), amountIn);

        amm.swap(address(tokenIn), amountIn);
    }

    /// @notice Burns held LP shares to withdraw underlying assets from the pool.
    /// @dev Bounds share burn quantity based on the handler's current LP token balance. Resets `kLast` to zero.
    /// @param shares Unbounded share quantity generated by the fuzzer to burn.
    function removeLiquidity(uint256 shares) public {
        uint256 userShares = amm.balanceOf(address(this));
        if (userShares == 0) return;

        // Reset kLast since removing liquidity reduces overall pool value
        kLast = 0;

        shares = bound(shares, 1, userShares);
        amm.removeLiquidity(shares);
    }
}
